all_apt = {
	'admin@338': ['admin@338'],
	'APT1': ['Comment Crew', ' Comment Group', ' Comment Panda', 'APT1'],
	'APT12': ['IXESHE', ' DynCalc', ' Numbered Panda', ' DNSCALC', 'APT12'],
	'APT16': ['APT16'],
	'APT17': ['Deputy Dog', 'APT17'],
	'APT18': ['TG-0416', ' Dynamite Panda', ' Threat Group-0416', 'APT18'],
	'APT19': ['Codoso', ' C0d0so0', ' Codoso Team', ' Sunshop Group', 'APT19'],
	'APT28': ['SNAKEMACKEREL', ' Swallowtail', ' Group 74', ' Sednit', ' Sofacy', ' Pawn Storm', ' Fancy Bear', ' STRONTIUM', ' Tsar Team', ' Threat Group-4127', ' TG-4127', 'APT28'],
	'APT29': ['YTTRIUM', ' The Dukes', ' Cozy Bear', ' CozyDuke', 'APT29'],
	'APT3': ['Gothic Panda', ' Pirpi', ' UPS Team', ' Buckeye', ' Threat Group-0110', ' TG-0110', 'APT3'],
	'APT30': ['APT30'],
	'APT32': ['SeaLotus', ' OceanLotus', ' APT-C-00', 'APT32'],
	'APT33': ['Elfin', 'APT33'],
	'APT37': ['ScarCruft', ' Reaper', ' Group123', ' TEMP.Reaper', 'APT37'],
	'APT38': ['APT38'],
	'APT39': ['Chafer', 'APT39'],
	'APT41': ['APT41'],
	'Axiom': ['Group 72', 'Axiom'],
	'BlackOasis': ['BlackOasis'],
	'BRONZE BUTLER': ['REDBALDKNIGHT', ' Tick', 'BRONZE BUTLER'],
	'Carbanak': ['Anunak', ' Carbon Spider', 'Carbanak'],
	'Charming Kitten': ['Charming Kitten'],
	'Cleaver': ['Threat Group 2889', ' TG-2889', 'Cleaver'],
	'Cobalt Group': ['Cobalt Gang', ' Cobalt Spider', 'Cobalt Group'],
	'CopyKittens': ['CopyKittens'],
	'Dark Caracal': ['Dark Caracal'],
	'Darkhotel': ['Darkhotel'],
	'DarkHydrus': ['DarkHydrus'],
	'Deep Panda': ['Shell Crew', ' WebMasters', ' KungFu Kittens', ' PinkPanther', ' Black Vine', 'Deep Panda'],
	'Dragonfly': ['Energetic Bear', 'Dragonfly'],
	'Dragonfly 2.0': ['Berserk Bear', 'Dragonfly 2.0'],
	'DragonOK': ['DragonOK'],
	'Dust Storm': ['Dust Storm'],
	'Elderwood': ['Elderwood Gang', ' Beijing Group', ' Sneaky Panda', 'Elderwood'],
	'Equation': ['Equation'],
	'FIN10': ['FIN10'],
	'FIN4': ['FIN4'],
	'FIN5': ['FIN5'],
	'FIN6': ['ITG08', 'FIN6'],
	'FIN7': ['FIN7'],
	'FIN8': ['FIN8'],
	'Gallmaker': ['Gallmaker'],
	'Gamaredon Group': ['Gamaredon Group'],
	'GCMAN': ['GCMAN'],
	'Gorgon Group': ['Gorgon Group'],
	'Group5': ['Group5'],
	'Honeybee': ['Honeybee'],
	'Ke3chang': ['APT15', ' Mirage', ' Vixen Panda', ' GREF', ' Playful Dragon', ' RoyalAPT', 'Ke3chang'],
	'Kimsuky': ['Velvet Chollima', 'Kimsuky'],
	'Lazarus Group': ['HIDDEN COBRA', ' Guardians of Peace', ' ZINC', ' NICKEL ACADEMY', 'Lazarus Group'],
	'Leafminer': ['Raspite', 'Leafminer'],
	'Leviathan': ['TEMP.Jumper', ' APT40', ' TEMP.Periscope', 'Leviathan'],
	'Lotus Blossom': ['DRAGONFISH', ' Spring Dragon', 'Lotus Blossom'],
	'Machete': ['El Machete', 'Machete'],
	'Magic Hound': ['Rocket Kitten', ' Operation Saffron Rose', ' Ajax Security Team', ' Operation Woolen-Goldfish', ' Newscaster', ' Cobalt Gypsy', ' APT35', 'Magic Hound'],
	'menuPass': ['Stone Panda', ' APT10', ' Red Apollo', ' CVNX', ' HOGFISH', 'menuPass'],
	'Moafee': ['Moafee'],
	'Molerats': ['Operation Molerats', ' Gaza Cybergang', 'Molerats'],
	'MuddyWater': ['Seedworm', ' TEMP.Zagros', 'MuddyWater'],
	'Naikon': ['Naikon'],
	'NEODYMIUM': ['NEODYMIUM'],
	'Night Dragon': ['Night Dragon'],
	'OilRig': ['IRN2', ' HELIX KITTEN', ' APT34', 'OilRig'],
	'Orangeworm': ['Orangeworm'],
	'Patchwork': ['Dropping Elephant', ' Chinastrats', ' MONSOON', ' Operation Hangover', 'Patchwork'],
	'PittyTiger': ['PittyTiger'],
	'PLATINUM': ['PLATINUM'],
	'Poseidon Group': ['Poseidon Group'],
	'PROMETHIUM': ['PROMETHIUM'],
	'Putter Panda': ['APT2', ' MSUpdater', 'Putter Panda'],
	'Rancor': ['Rancor'],
	'RTM': ['RTM'],
	'Sandworm Team': ['Quedagh', ' VOODOO BEAR', 'Sandworm Team'],
	'Scarlet Mimic': ['Scarlet Mimic'],
	'Silence': ['Silence'],
	'SilverTerrier': ['SilverTerrier'],
	'Soft Cell': ['Soft Cell'],
	'Sowbug': ['Sowbug'],
	'Stealth Falcon': ['Stealth Falcon'],
	'Stolen Pencil': ['Stolen Pencil'],
	'Strider': ['ProjectSauron', 'Strider'],
	'Suckfly': ['Suckfly'],
	'TA459': ['TA459'],
	'TA505': ['TA505'],
	'Taidoor': ['Taidoor'],
	'TEMP.Veles': ['XENOTIME', 'TEMP.Veles'],
	'The White Company': ['The White Company'],
	'Threat Group-1314': ['TG-1314', 'Threat Group-1314'],
	'Threat Group-3390': ['TG-3390', ' Emissary Panda', ' BRONZE UNION', ' APT27', ' Iron Tiger', ' LuckyMouse', 'Threat Group-3390'],
	'Thrip': ['Thrip'],
	'Tropic Trooper': ['KeyBoy', 'Tropic Trooper'],
	'Turla': ['Waterbug', ' WhiteBear', ' VENOMOUS BEAR', ' Snake', ' Krypton', 'Turla'],
	'Winnti Group': ['Blackfly', 'Winnti Group'],
	'WIRTE': ['WIRTE'],
    "Donot Team": ['Donot Team']
}


categories = ['APT攻击', '可疑', '恶意软件']